<?php

$_tmp = [
    'menu_name' => 'mmxUsers',
    'menu_desc' => 'Convenient management of MODX users',
    'actions' => [
        'create' => 'Create',
        'edit' => 'Edit',
        'submit' => 'Submit',
        'cancel' => 'Cancel',
        'delete' => 'Delete',
        'invite' => 'Invite',
        'more' => 'Show More',
    ],
    'models' => [
        'user' => [
            'title_one' => 'User',
            'title_many' => 'Users',
            'id' => 'Id',
            'username' => 'Username',
            'fullname' => 'Full Name',
            'email' => 'Email',
            'group' => 'Main Group',
            'active' => 'Active',
            'blocked' => 'Blocked',
            'sudo' => 'Sudo User',
            'photo' => 'Photo',
            'gender' => 'Gender',
            'gender_male' => 'Male',
            'gender_female' => 'Female',
            'gender_other' => 'Other',
            'dob' => 'Date of Birth',
            'comment' => 'Company',
            'createdon' => 'Created On',
            'status' => [
                'any' => 'Any',
                'active' => 'Active',
                'inactive' => 'Inactive',
            ],
            'extended' => [
                'pay_afterwards' => 'Pay afterwards',
                'main_branch' => 'Main branch',
                'max_days_order_overview' => 'Max days order overview',
                'logo' => 'Logo',
                'company_logo' => 'Company Logo',
            ],
            'settings' => [
                'twofactoroptions' => '2FA',
            ],
            'password' => [
                'new' => 'New Password',
                'specified' => 'Enter Password',
                'confirm' => 'Confirm Password',
            ],
            'website' => 'Website',
            'phone' => 'Phone',
            'mobilephone' => 'Mobile phone',
            'fax' => 'Fax',
            'country' => 'Country',
            'state' => 'State',
            'city' => 'City',
            'zip' => 'Zip',
            'address' => 'Address',
            'tabs' => [
                'general' => 'General',
                'extended' => 'Extended Fields',
                'settings' => 'Settings',
                'groups' => 'User Groups',
                'addresses' => 'Addresses',
            ],
            'filter' => [
                'any' => 'All Users',
                'active' => 'Active',
                'inactive' => 'Inactive',
            ],
        ],
        'user_group' => [
            'title_one' => 'User Group',
            'title_many' => 'User Groups',
            'id' => 'Id',
            'name' => 'Name',
            'description' => 'Description',
            'rank' => 'Rank',
            'parent' => 'Parent',
            'resource_group' => [
                'create' => 'Also Create Resource Group',
                'desc' => 'Specify Contexts that this User Group should be able to view.',
                'select' => 'Select Context...',
            ],
            'filter_any' => 'All Groups',
        ],
        'user_group_role' => [
            'title_one' => 'User Role',
            'title_many' => 'User Roles',
            'id' => 'Id',
            'name' => 'Name',
            'description' => 'Description',
            'authority' => 'Authority',
        ],
        'user_group_member' => [
            'title_one' => 'User Group Member',
            'title_many' => 'User Group Members',
            'id' => 'Member Id',
            'user_group' => 'User Group',
            'member' => 'User',
            'role' => 'User Role',
            'rank' => 'Rank',
        ],
        'user_setting' => [
            'title_one' => 'Setting',
            'title_many' => 'Settings',
            'key' => 'Key',
            'value' => 'Value',
            'xtype' => 'Type',
            'namespace' => 'Namespace',
            'area' => 'Area',
            'editedon' => 'Edited On',
            'types' => [
                'textfield' => 'Text Field',
                'textarea' => 'Text Area',
                'numberfield' => 'Number Field',
                'combo-boolean' => 'Boolean',
                'text-password' => 'Password Field',
                'modx-combo-category' => 'Categories',
                'modx-combo-charset' => 'Charsets',
                'modx-combo-country' => 'Countries',
                'modx-combo-context' => 'Contexts',
                'modx-combo-namespace' => 'Namespaces',
                'modx-combo-template' => 'Templates',
                'modx-combo-user' => 'Users',
                'modx-combo-usergroup' => 'User Groups',
                'modx-combo-language' => 'Languages',
                'modx-combo-source' => 'Sources',
                'modx-combo-source-type' => 'Source Types',
                'modx-combo-manager-theme' => 'Manager Themes',
                'modx-grid-json' => 'JSON Grid',
            ],
        ],
        'commerce' => [
            'address' => [
                'title_one' => 'Address',
                'title_many' => 'Addresses',
                'id' => 'Id',
                'type' => 'Type',
                'last_used' => 'Last Used',
                'company' => 'Company',
                // 'user' => 'User',
                'receiver' => 'Receiver',
                'fullname' => 'Fullname',
                'firstname' => 'Firstname',
                'lastname' => 'Lastname',
                'address' => 'Address',
                'address1' => 'Address 1',
                'address2' => 'Address 2',
                'address3' => 'Address 3',
                'zip' => 'Zip',
                'city' => 'City',
                'state' => 'State',
                'country' => 'Country',
                'phone' => 'Phone',
                'mobile' => 'Mobile',
                'notes' => 'Notes',
                'email' => 'Email',
                'types' => [
                    'any' => 'Filter by Type',
                    'shipping' => 'Shipping',
                    'billing' => 'Billing',
                ],
            ],
        ],
    ],
    'components' => [
        'no_data' => 'Nothing to display',
        'no_results' => 'Nothing found',
        'records' => 'No records | 1 record | {total} records',
        'query' => 'Search...',
        'delete' => [
            'title' => 'Confirmation required',
            'confirm' => 'Are you sure you want to delete this entry?',
        ],
    ],
    /* 'snippets' => [
        'nocss' => 'Do not load frontend styles',
    ], */
    'success' => [
        'user' => [
            'invited' => 'The invitation was successfully sent!',
        ]
    ],
    'errors' => [
        'user' => [
            'image_required' => 'Please select an image!',
        ],
    ],
];

/** @var array $_lang */
$_lang = array_merge($_lang, MMX\Users\App::prepareLexicon($_tmp, MMX\Users\App::NAMESPACE));

$_tmp = [
    'some-setting' => 'Setting title',
    'some-setting_desc' => 'Some setting description',
];
$_lang = array_merge($_lang, MMX\Users\App::prepareLexicon($_tmp, 'setting_' . MMX\Users\App::NAMESPACE));

unset($_tmp);